name: Go
on:
  push:
    branches:
      - zdns
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 1.15.x, 1.16.x ]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  release:
    # Don't tag until the PR is merged. We do, however, want the first job to run so that we check build/test integrity.
    # The logic here is a bit weird. We only kick off this action on pushes to master and PRs to master. 
    # So we can safely use a negative check for the pr event to ensure we're not releasing on PRs.
    # If other events are used to trigger the overall job, see
    if: ${{ github.event_name != 'pull_request' }}
    needs: build
    name: Release Next Tag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 1.15.x, 1.16.x ]
    steps:
    - name: Check branch
      shell: bash
      run: echo ${GITHUB_REF_NAME}
    - name: Release Tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: patch
        default_prerelease_bump: patch
        release_branches: master
        dry_run: true