name: Go
on:
  push:
    branches:
      - zdns
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 1.17.x ]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

#TODO: handle case where we don't update miekg in between

  release:
    # Don't tag until the PR is merged. We do, however, want the first job to run so that we check build/test integrity.
    # The logic here is a bit weird. We only kick off this action on pushes to master and PRs to master. 
    # So we can safely use a negative check for the pr event to ensure we're not releasing on PRs.
    # If other events are used to trigger the overall job, see
    if: ${{ github.ref == 'refs/heads/zdns' }}
    needs: build
    name: Release Next Tag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 1.17.x ]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Get Latest Tag for zdns
      id: get_tag
      shell: bash
      run: |
        LATEST_TAG=$(git tag --merged | sort -V | tail -n 1); \
        if [[ "${LATEST_TAG}" == *-zdns-* ]]; then \
            echo "already tagged a release here, using next version"; \
            ZDNS_RELEASE_NUM=$(echo ${LATEST_TAG} | sed 's|.*-zdns-\(.*\)|\1|'); \
            ZDNS_RELEASE_NUM=$((ZDNS_RELEASE_NUM+1)); \
            echo $ZDNS_RELEASE_NUM; \
            TAG_PORTION=$(echo ${LATEST_TAG} | sed 's|\(.*\)-zdns-.*|\1|'); \
            echo $TAG_PORTION; \
            ZDNS_TAG="${TAG_PORTION}-zdns-${ZDNS_RELEASE_NUM}"; \
            echo $ZDNS_TAG; \
        else \
            echo "cleared hot"; \
            ZDNS_TAG="${LATEST_TAG}-zdns-0"; \
            echo $ZDNS_TAG; \
        fi; \
        echo "::set-output name=ZDNS_TAG::${ZDNS_TAG}";
    - name: Release Tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{ steps.get_tag.outputs.ZDNS_TAG }}
        release_branches: zdns
        dry_run: true